simple_graphical_vector_editor: Controller Class Reference
Controller Class Reference
Controller
#include <controller.h>
Public Member Functions
void CreateNewDocument ()
Method for create new document.
void ImportDocumentFromFile ()
Method for imort document from file.
void ExportDocumentToFile ()
Method for export document to file.
std::shared_ptr< Square > CreateSquare ()
Method for create square.
std::shared_ptr< Polygon > CreatePolygon ()
Method for create polygon.
std::shared_ptr< Triangle > CreateTriangle ()
Method for create triangle.
std::shared_ptr< Circle > CreateCircle ()
Method for create circle.
void DeleteGraphicalPrimitive (std::shared_ptr< IGraphicalPrimitive > primitive)
Method for delete graphical primitive.
Private Attributes
std::unique_ptr< Document > _document
Field of current work document.
Detailed Description
Definition at line 26 of file controller.h.
Member Function Documentation
CreateCircle()
std::shared_ptr< Circle > Controller::CreateCircle ()
Method for create circle.
Returns
Pointer to circle.
Definition at line 71 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if(_document)
    {
        return _document->AddCircle();
    }
    else
    {
        std::cout << "No opened document" << std::endl;
        return nullptr;
    }
}
Referenced by main().
CreateNewDocument()
void Controller::CreateNewDocument ()
Method for create new document.
Definition at line 4 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    _document = std::make_unique<Document>();
}
Referenced by main().
CreatePolygon()
std::shared_ptr< Polygon > Controller::CreatePolygon ()
Method for create polygon.
Returns
Pointer to polygon.
Definition at line 43 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if(_document)
    {
        return _document->AddPolygon();
    }
    else
    {
        std::cout << "No opened document" << std::endl;
        return nullptr;
    }
}
Referenced by main().
CreateSquare()
std::shared_ptr< Square > Controller::CreateSquare ()
Method for create square.
Returns
Pointer to square.
Definition at line 29 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if(_document)
    {
        return _document->AddSquare();
    }
    else
    {
        std::cout << "No opened document" << std::endl;
        return nullptr;
    }
}
CreateTriangle()
std::shared_ptr< Triangle > Controller::CreateTriangle ()
Method for create triangle.
Returns
Pointer to triangle.
Definition at line 57 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if(_document)
    {
        return _document->AddTriangle();
    }
    else
    {
        std::cout << "No opened document" << std::endl;
        return nullptr;
    }
}
DeleteGraphicalPrimitive()
void Controller::DeleteGraphicalPrimitive (std::shared_ptr< IGraphicalPrimitive > primitive)
Method for delete graphical primitive.
Parameters
primitive is any graphical primitive in current work document.
Definition at line 85 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if(_document)
    {
        return _document->DeletePrimitive(primitive);
    }
    else
    {
        std::cout << "No opened document" << std::endl;
    }
}
Referenced by main().
ExportDocumentToFile()
void Controller::ExportDocumentToFile ()
Method for export document to file.
Definition at line 16 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    if (_document)
    {
        std::cout << "Document exported" << std::endl;
    }
    else
    {
        std::cout << "No document for export" << std::endl;
    }
}
ImportDocumentFromFile()
void Controller::ImportDocumentFromFile ()
Method for imort document from file.
Definition at line 10 of file controller.cpp.
{
    std::cout << __PRETTY_FUNCTION__ << std::endl;
    _document = std::make_unique<Document>();
}
Member Data Documentation
_document
std::unique_ptr<Document> Controller::_document private
Field of current work document.
Definition at line 31 of file controller.h.
Referenced by CreateCircle(), CreateNewDocument(), CreatePolygon(), CreateSquare(), CreateTriangle(), DeleteGraphicalPrimitive(), ExportDocumentToFile(), and ImportDocumentFromFile().
The documentation for this class was generated from the following files:
controller.h
controller.cpp